language: cpp

dist: trusty

apt:
  addons:
    sources:
      - george-edison55-cmake-3.x
    packages:
      - cmake
      - cmake-data

compiler:
  - gcc
  - clang

install:
  - export LD_LIBRARY_PATH=$(if [[ $CC == "clang" ]]; then echo -n '/usr/local/clang/lib'; fi)

script:
  - ctest -VV -S cmake/TestVecCore.cmake
