set(FLAGS_SSE    "-xsse")
set(FLAGS_SSE2   "-xsse2")
set(FLAGS_SSE3   "-xsse3")
set(FLAGS_SSSE3  "-xssse3")
set(FLAGS_SSE41  "-xsse4.1")
set(FLAGS_SSE42  "-xsse4.2")
set(FLAGS_AVX    "-xAVX")
set(FLAGS_AVX2   "-xCORE-AVX2")
set(FLAGS_NATIVE "-march=native")

if (MIC)
	set(FLAGS_AVX512 "-xMIC-AVX512")
else()
	set(FLAGS_AVX512 "-xCORE-AVX512")
endif()

set(CMAKE_CXX_FLAGS_DEBUG          "-DDEBUG  -g -O0")
set(CMAKE_CXX_FLAGS_RELEASE        "-DNDEBUG    -O3 -restrict")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-DDEBUG  -g -O3 -restrict")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -fPIC -restrict")
set(CMAKE_EXE_LINKER_FLAGS "")
