name: GitHub Actions

permissions:
  contents: read

on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  CDASH: ${{ vars.CDASH }}
  CMAKE_ARGS: "-DCMAKE_CXX_STANDARD=20"
  CMAKE_VERBOSE_MAKEFILE: true
  CTEST_OUTPUT_ON_FAILURE: true

jobs:
  linux:
    name: Linux (${{ matrix.compiler}}, ${{ matrix.target }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        compiler: [ "gcc", "clang" ]
        target: [ "sse4.2", "avx2", "native" ]

    env:
      CC: ${{ matrix.compiler }}

    steps:
    - name: Clone repository
      uses: actions/checkout@v7

    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y cmake pkg-config libgd-dev ${{matrix.compiler}}

    - name: Build and Test with CTest
      run: env CC=${CC} CXX=${CC/g*/g++} ctest -VV -S ctest.cmake,${{matrix.target}}

  macos:
    name: macOS ${{ matrix.version }}
    runs-on: macos-${{ matrix.version }}

    strategy:
      fail-fast: true
      matrix:
        version: [ "15", "26" ]

    env:
      CC: clang
      CXX: clang++

    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: brew install gd

    - name: Build and Test with CTest
      run: ctest -VV -S ctest.cmake

  windows:
    name: Windows
    runs-on: windows-latest

    strategy:
      fail-fast: true
      matrix:
        target: [ sse2, avx2 ]

    steps:
    - name: Clone repository
      uses: actions/checkout@v7

    - name: Build and Test with CTest
      run: ctest -VV -S ctest.cmake,${{matrix.target}}
